// <auto-generated />
namespace LATIENDA.Infraestructura.Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NuevasEntidades_Productos_Marcas_Rubros_Usuarios_Empleados : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NuevasEntidades_Productos_Marcas_Rubros_Usuarios_Empleados));
        
        string IMigrationMetadata.Id
        {
            get { return "202108311907526_NuevasEntidades_Productos_Marcas_Rubros_Usuarios_Empleados"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
