// <auto-generated />
namespace LATIENDA.Infraestructura.Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SemodificolaclaseVentaLineadeventa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SemodificolaclaseVentaLineadeventa));
        
        string IMigrationMetadata.Id
        {
            get { return "202203171900262_Se modifico la clase Venta Linea de venta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
