// <auto-generated />
namespace LATIENDA.Infraestructura.Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SemodificaronlasclasesCOLORMARCARUBRO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SemodificaronlasclasesCOLORMARCARUBRO));
        
        string IMigrationMetadata.Id
        {
            get { return "202201311604447_Se modificaron las clases COLOR MARCA RUBRO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
